title: Recide Documentation
description: Provides utilities for defining standard ex-info forms, as well as the capacity for checking at compile-time that they are being used as intended
theme: jekyll-theme-tactile
